/*
auth

auth

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateUserConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateUserConfigRequest{}

// UpdateUserConfigRequest struct for UpdateUserConfigRequest
type UpdateUserConfigRequest struct {
	MfaType NullableUserMFAType `json:"mfa_type,omitempty"`
}

// NewUpdateUserConfigRequest instantiates a new UpdateUserConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateUserConfigRequest() *UpdateUserConfigRequest {
	this := UpdateUserConfigRequest{}
	return &this
}

// NewUpdateUserConfigRequestWithDefaults instantiates a new UpdateUserConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateUserConfigRequestWithDefaults() *UpdateUserConfigRequest {
	this := UpdateUserConfigRequest{}
	return &this
}

// GetMfaType returns the MfaType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateUserConfigRequest) GetMfaType() UserMFAType {
	if o == nil || IsNil(o.MfaType.Get()) {
		var ret UserMFAType
		return ret
	}
	return *o.MfaType.Get()
}

// GetMfaTypeOk returns a tuple with the MfaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateUserConfigRequest) GetMfaTypeOk() (*UserMFAType, bool) {
	if o == nil {
		return nil, false
	}
	return o.MfaType.Get(), o.MfaType.IsSet()
}

// HasMfaType returns a boolean if a field has been set.
func (o *UpdateUserConfigRequest) HasMfaType() bool {
	if o != nil && o.MfaType.IsSet() {
		return true
	}

	return false
}

// SetMfaType gets a reference to the given NullableUserMFAType and assigns it to the MfaType field.
func (o *UpdateUserConfigRequest) SetMfaType(v UserMFAType) {
	o.MfaType.Set(&v)
}
// SetMfaTypeNil sets the value for MfaType to be an explicit nil
func (o *UpdateUserConfigRequest) SetMfaTypeNil() {
	o.MfaType.Set(nil)
}

// UnsetMfaType ensures that no value is present for MfaType, not even an explicit nil
func (o *UpdateUserConfigRequest) UnsetMfaType() {
	o.MfaType.Unset()
}

func (o UpdateUserConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateUserConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.MfaType.IsSet() {
		toSerialize["mfa_type"] = o.MfaType.Get()
	}
	return toSerialize, nil
}

type NullableUpdateUserConfigRequest struct {
	value *UpdateUserConfigRequest
	isSet bool
}

func (v NullableUpdateUserConfigRequest) Get() *UpdateUserConfigRequest {
	return v.value
}

func (v *NullableUpdateUserConfigRequest) Set(val *UpdateUserConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateUserConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateUserConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateUserConfigRequest(val *UpdateUserConfigRequest) *NullableUpdateUserConfigRequest {
	return &NullableUpdateUserConfigRequest{value: val, isSet: true}
}

func (v NullableUpdateUserConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateUserConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


