/*
auth

auth

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenRequestOneOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenRequestOneOf3{}

// TokenRequestOneOf3 struct for TokenRequestOneOf3
type TokenRequestOneOf3 struct {
	Code string `json:"code"`
	GrantType string `json:"grant_type"`
	Scope NullableString `json:"scope,omitempty"`
}

type _TokenRequestOneOf3 TokenRequestOneOf3

// NewTokenRequestOneOf3 instantiates a new TokenRequestOneOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenRequestOneOf3(code string, grantType string) *TokenRequestOneOf3 {
	this := TokenRequestOneOf3{}
	this.Code = code
	this.GrantType = grantType
	return &this
}

// NewTokenRequestOneOf3WithDefaults instantiates a new TokenRequestOneOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenRequestOneOf3WithDefaults() *TokenRequestOneOf3 {
	this := TokenRequestOneOf3{}
	return &this
}

// GetCode returns the Code field value
func (o *TokenRequestOneOf3) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *TokenRequestOneOf3) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *TokenRequestOneOf3) SetCode(v string) {
	o.Code = v
}

// GetGrantType returns the GrantType field value
func (o *TokenRequestOneOf3) GetGrantType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GrantType
}

// GetGrantTypeOk returns a tuple with the GrantType field value
// and a boolean to check if the value has been set.
func (o *TokenRequestOneOf3) GetGrantTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantType, true
}

// SetGrantType sets field value
func (o *TokenRequestOneOf3) SetGrantType(v string) {
	o.GrantType = v
}

// GetScope returns the Scope field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenRequestOneOf3) GetScope() string {
	if o == nil || IsNil(o.Scope.Get()) {
		var ret string
		return ret
	}
	return *o.Scope.Get()
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenRequestOneOf3) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scope.Get(), o.Scope.IsSet()
}

// HasScope returns a boolean if a field has been set.
func (o *TokenRequestOneOf3) HasScope() bool {
	if o != nil && o.Scope.IsSet() {
		return true
	}

	return false
}

// SetScope gets a reference to the given NullableString and assigns it to the Scope field.
func (o *TokenRequestOneOf3) SetScope(v string) {
	o.Scope.Set(&v)
}
// SetScopeNil sets the value for Scope to be an explicit nil
func (o *TokenRequestOneOf3) SetScopeNil() {
	o.Scope.Set(nil)
}

// UnsetScope ensures that no value is present for Scope, not even an explicit nil
func (o *TokenRequestOneOf3) UnsetScope() {
	o.Scope.Unset()
}

func (o TokenRequestOneOf3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenRequestOneOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["grant_type"] = o.GrantType
	if o.Scope.IsSet() {
		toSerialize["scope"] = o.Scope.Get()
	}
	return toSerialize, nil
}

func (o *TokenRequestOneOf3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"grant_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenRequestOneOf3 := _TokenRequestOneOf3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenRequestOneOf3)

	if err != nil {
		return err
	}

	*o = TokenRequestOneOf3(varTokenRequestOneOf3)

	return err
}

type NullableTokenRequestOneOf3 struct {
	value *TokenRequestOneOf3
	isSet bool
}

func (v NullableTokenRequestOneOf3) Get() *TokenRequestOneOf3 {
	return v.value
}

func (v *NullableTokenRequestOneOf3) Set(val *TokenRequestOneOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenRequestOneOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenRequestOneOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenRequestOneOf3(val *TokenRequestOneOf3) *NullableTokenRequestOneOf3 {
	return &NullableTokenRequestOneOf3{value: val, isSet: true}
}

func (v NullableTokenRequestOneOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenRequestOneOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


