/*
auth

auth

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginationServiceAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginationServiceAccount{}

// PaginationServiceAccount struct for PaginationServiceAccount
type PaginationServiceAccount struct {
	HasMore bool `json:"has_more"`
	Items []PaginationServiceAccountItemsInner `json:"items"`
}

type _PaginationServiceAccount PaginationServiceAccount

// NewPaginationServiceAccount instantiates a new PaginationServiceAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginationServiceAccount(hasMore bool, items []PaginationServiceAccountItemsInner) *PaginationServiceAccount {
	this := PaginationServiceAccount{}
	this.HasMore = hasMore
	this.Items = items
	return &this
}

// NewPaginationServiceAccountWithDefaults instantiates a new PaginationServiceAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginationServiceAccountWithDefaults() *PaginationServiceAccount {
	this := PaginationServiceAccount{}
	return &this
}

// GetHasMore returns the HasMore field value
func (o *PaginationServiceAccount) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *PaginationServiceAccount) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *PaginationServiceAccount) SetHasMore(v bool) {
	o.HasMore = v
}

// GetItems returns the Items field value
func (o *PaginationServiceAccount) GetItems() []PaginationServiceAccountItemsInner {
	if o == nil {
		var ret []PaginationServiceAccountItemsInner
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PaginationServiceAccount) GetItemsOk() ([]PaginationServiceAccountItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PaginationServiceAccount) SetItems(v []PaginationServiceAccountItemsInner) {
	o.Items = v
}

func (o PaginationServiceAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginationServiceAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["has_more"] = o.HasMore
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *PaginationServiceAccount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"has_more",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginationServiceAccount := _PaginationServiceAccount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginationServiceAccount)

	if err != nil {
		return err
	}

	*o = PaginationServiceAccount(varPaginationServiceAccount)

	return err
}

type NullablePaginationServiceAccount struct {
	value *PaginationServiceAccount
	isSet bool
}

func (v NullablePaginationServiceAccount) Get() *PaginationServiceAccount {
	return v.value
}

func (v *NullablePaginationServiceAccount) Set(val *PaginationServiceAccount) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginationServiceAccount) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginationServiceAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginationServiceAccount(val *PaginationServiceAccount) *NullablePaginationServiceAccount {
	return &NullablePaginationServiceAccount{value: val, isSet: true}
}

func (v NullablePaginationServiceAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginationServiceAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


