/*
auth

auth

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateUserPhoneNumber type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUserPhoneNumber{}

// CreateUserPhoneNumber struct for CreateUserPhoneNumber
type CreateUserPhoneNumber struct {
	PhoneNumber string `json:"phone_number"`
}

type _CreateUserPhoneNumber CreateUserPhoneNumber

// NewCreateUserPhoneNumber instantiates a new CreateUserPhoneNumber object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUserPhoneNumber(phoneNumber string) *CreateUserPhoneNumber {
	this := CreateUserPhoneNumber{}
	this.PhoneNumber = phoneNumber
	return &this
}

// NewCreateUserPhoneNumberWithDefaults instantiates a new CreateUserPhoneNumber object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUserPhoneNumberWithDefaults() *CreateUserPhoneNumber {
	this := CreateUserPhoneNumber{}
	return &this
}

// GetPhoneNumber returns the PhoneNumber field value
func (o *CreateUserPhoneNumber) GetPhoneNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
func (o *CreateUserPhoneNumber) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// SetPhoneNumber sets field value
func (o *CreateUserPhoneNumber) SetPhoneNumber(v string) {
	o.PhoneNumber = v
}

func (o CreateUserPhoneNumber) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUserPhoneNumber) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phone_number"] = o.PhoneNumber
	return toSerialize, nil
}

func (o *CreateUserPhoneNumber) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phone_number",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateUserPhoneNumber := _CreateUserPhoneNumber{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateUserPhoneNumber)

	if err != nil {
		return err
	}

	*o = CreateUserPhoneNumber(varCreateUserPhoneNumber)

	return err
}

type NullableCreateUserPhoneNumber struct {
	value *CreateUserPhoneNumber
	isSet bool
}

func (v NullableCreateUserPhoneNumber) Get() *CreateUserPhoneNumber {
	return v.value
}

func (v *NullableCreateUserPhoneNumber) Set(val *CreateUserPhoneNumber) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUserPhoneNumber) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUserPhoneNumber) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUserPhoneNumber(val *CreateUserPhoneNumber) *NullableCreateUserPhoneNumber {
	return &NullableCreateUserPhoneNumber{value: val, isSet: true}
}

func (v NullableCreateUserPhoneNumber) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUserPhoneNumber) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


