/*
auth

auth

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginationUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginationUser{}

// PaginationUser struct for PaginationUser
type PaginationUser struct {
	HasMore bool `json:"has_more"`
	Items []PaginationUserItemsInner `json:"items"`
}

type _PaginationUser PaginationUser

// NewPaginationUser instantiates a new PaginationUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginationUser(hasMore bool, items []PaginationUserItemsInner) *PaginationUser {
	this := PaginationUser{}
	this.HasMore = hasMore
	this.Items = items
	return &this
}

// NewPaginationUserWithDefaults instantiates a new PaginationUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginationUserWithDefaults() *PaginationUser {
	this := PaginationUser{}
	return &this
}

// GetHasMore returns the HasMore field value
func (o *PaginationUser) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *PaginationUser) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *PaginationUser) SetHasMore(v bool) {
	o.HasMore = v
}

// GetItems returns the Items field value
func (o *PaginationUser) GetItems() []PaginationUserItemsInner {
	if o == nil {
		var ret []PaginationUserItemsInner
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PaginationUser) GetItemsOk() ([]PaginationUserItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PaginationUser) SetItems(v []PaginationUserItemsInner) {
	o.Items = v
}

func (o PaginationUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginationUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["has_more"] = o.HasMore
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *PaginationUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"has_more",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginationUser := _PaginationUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginationUser)

	if err != nil {
		return err
	}

	*o = PaginationUser(varPaginationUser)

	return err
}

type NullablePaginationUser struct {
	value *PaginationUser
	isSet bool
}

func (v NullablePaginationUser) Get() *PaginationUser {
	return v.value
}

func (v *NullablePaginationUser) Set(val *PaginationUser) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginationUser) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginationUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginationUser(val *PaginationUser) *NullablePaginationUser {
	return &NullablePaginationUser{value: val, isSet: true}
}

func (v NullablePaginationUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginationUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


