/*
auth

auth

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenRequestOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenRequestOneOf2{}

// TokenRequestOneOf2 struct for TokenRequestOneOf2
type TokenRequestOneOf2 struct {
	ClientId string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	GrantType string `json:"grant_type"`
}

type _TokenRequestOneOf2 TokenRequestOneOf2

// NewTokenRequestOneOf2 instantiates a new TokenRequestOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenRequestOneOf2(clientId string, clientSecret string, grantType string) *TokenRequestOneOf2 {
	this := TokenRequestOneOf2{}
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	this.GrantType = grantType
	return &this
}

// NewTokenRequestOneOf2WithDefaults instantiates a new TokenRequestOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenRequestOneOf2WithDefaults() *TokenRequestOneOf2 {
	this := TokenRequestOneOf2{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *TokenRequestOneOf2) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *TokenRequestOneOf2) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *TokenRequestOneOf2) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *TokenRequestOneOf2) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *TokenRequestOneOf2) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *TokenRequestOneOf2) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetGrantType returns the GrantType field value
func (o *TokenRequestOneOf2) GetGrantType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GrantType
}

// GetGrantTypeOk returns a tuple with the GrantType field value
// and a boolean to check if the value has been set.
func (o *TokenRequestOneOf2) GetGrantTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantType, true
}

// SetGrantType sets field value
func (o *TokenRequestOneOf2) SetGrantType(v string) {
	o.GrantType = v
}

func (o TokenRequestOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenRequestOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client_id"] = o.ClientId
	toSerialize["client_secret"] = o.ClientSecret
	toSerialize["grant_type"] = o.GrantType
	return toSerialize, nil
}

func (o *TokenRequestOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"client_id",
		"client_secret",
		"grant_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenRequestOneOf2 := _TokenRequestOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenRequestOneOf2)

	if err != nil {
		return err
	}

	*o = TokenRequestOneOf2(varTokenRequestOneOf2)

	return err
}

type NullableTokenRequestOneOf2 struct {
	value *TokenRequestOneOf2
	isSet bool
}

func (v NullableTokenRequestOneOf2) Get() *TokenRequestOneOf2 {
	return v.value
}

func (v *NullableTokenRequestOneOf2) Set(val *TokenRequestOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenRequestOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenRequestOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenRequestOneOf2(val *TokenRequestOneOf2) *NullableTokenRequestOneOf2 {
	return &NullableTokenRequestOneOf2{value: val, isSet: true}
}

func (v NullableTokenRequestOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenRequestOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


